# ═══════════════════════════════════════════════════════════════
# Unified FQRN Map Aggregation
# Aggregates FQRN maps from all applications and shared resources
# ═══════════════════════════════════════════════════════════════
#
# AUTO-GENERATED - DO NOT EDIT MANUALLY
# This file is auto-generated (similar to terraform.tfvars)
# Generated by: bin/generate_all_fqrn.py
# Template: templates/terraform_fqrn.tf.j2
#

locals {
  # Shared infrastructure FQRN maps

  compartment_fqrns = module.compartments.fqrn_map


  vcn_fqrns = merge([
    for k, m in module.vcns : m.fqrn_map
  ]...)


  subnet_fqrns = merge([
    for k, m in module.subnets : m.fqrn_map
  ]...)



  # APP1 module FQRN maps

  app1_nsgs_fqrns = merge([
    for k, m in module.app1_nsgs : m.fqrn_map
  ]...)


  app1_compute_instances_fqrns = merge([
    for k, m in module.app1_compute_instances : m.fqrn_map
  ]...)



  # APP2 module FQRN maps

  app2_nsgs_fqrns = merge([
    for k, m in module.app2_nsgs : m.fqrn_map
  ]...)


  app2_compute_instances_fqrns = merge([
    for k, m in module.app2_compute_instances : m.fqrn_map
  ]...)



  # Combined FQRN maps for layer dependencies
  compartment_and_vcn_fqrns = merge(
    local.compartment_fqrns,
    local.vcn_fqrns
  )

  compartment_vcn_subnet_fqrns = merge(
    local.compartment_fqrns,
    local.vcn_fqrns,
    local.subnet_fqrns
  )

  # Network FQRNs base (without app NSGs to avoid cycles during NSG creation)
  network_fqrns_base = merge(
    local.compartment_fqrns,
    local.vcn_fqrns,
    local.subnet_fqrns
  )

  # Network FQRNs including all NSGs (for use after NSGs are created)
  network_fqrns = merge(
    local.network_fqrns_base,



    local.app1_nsgs_fqrns,  # Include APP1 NSGs







    local.app2_nsgs_fqrns,  # Include APP2 NSGs





  )

  # Unified FQRN map - merges ALL resources from all applications
  fqrns = merge(

    local.compartment_fqrns,

    local.vcn_fqrns,

    local.subnet_fqrns,



    local.app1_nsgs_fqrns,

    local.app1_compute_instances_fqrns,



    local.app2_nsgs_fqrns,

    local.app2_compute_instances_fqrns,


  )

  # Unified FQRN map for output (alias)
  unified_fqrn_map = local.fqrns
}
