# ═══════════════════════════════════════════════════════════════
# Unified FQRN Map Aggregation
# Aggregates FQRN maps from all applications and shared resources
# ═══════════════════════════════════════════════════════════════
#
# AUTO-GENERATED - DO NOT EDIT MANUALLY
# This file is auto-generated (similar to terraform.tfvars)
# Generated by: bin/generate_fqrn.sh
# Template: templates/terraform_fqrn.tf.j2
#

locals {
  # Shared infrastructure FQRN maps
  bastions_fqrns = merge([
    for k, m in module.bastions : m.fqrn_map
  ]...)
  compartments_fqrns = module.compartments.fqrn_map
  log_groups_fqrns = merge([
    for k, m in module.log_groups : m.fqrn_map
  ]...)
  vcns_fqrns = merge([
    for k, m in module.vcns : m.fqrn_map
  ]...)
  subnets_fqrns = merge([
    for k, m in module.subnets : m.fqrn_map
  ]...)
  infra_zones_fqrns = merge([
    for k, m in module.infra_zones : m.fqrn_map
  ]...)
  # APP1 module FQRN maps
  app1_compute_instances_fqrns = merge([
    for k, m in module.app1_compute_instances : m.fqrn_map
  ]...)
  app1_nsgs_fqrns = merge([
    for k, m in module.app1_nsgs : m.fqrn_map
  ]...)
  # APP2 module FQRN maps
  app2_nsgs_fqrns = merge([
    for k, m in module.app2_nsgs : m.fqrn_map
  ]...)

  # ═══════════════════════════════════════════════════════════════
  # Combined FQRN maps for layer dependencies (dynamically built)
  # ═══════════════════════════════════════════════════════════════
  # Layer 1+2: Compartments and VCNs
  compartment_and_vcn_fqrns = merge(
    local.compartments_fqrns,
    local.vcns_fqrns
  )
  # Layer 1+2+3: Compartments, VCNs, and Subnets
  compartment_vcn_subnet_fqrns = merge(
    local.compartments_fqrns,
    local.vcns_fqrns,
    local.subnets_fqrns
  )

  # Network FQRNs base (without app NSGs to avoid cycles during NSG creation)
  network_fqrns_base = merge(
    local.compartments_fqrns,
    local.vcns_fqrns,
    local.subnets_fqrns
  )

  # Network FQRNs including all NSGs (for use after NSGs are created)
  network_fqrns = merge(
    local.network_fqrns_base,
    local.app1_nsgs_fqrns,  # Include APP1 NSGs
    local.app2_nsgs_fqrns,  # Include APP2 NSGs
  )

  # Infrastructure FQRNs (network + bastions, for use by zones)
  infra_fqrns = merge(
    local.compartments_fqrns,
    local.vcns_fqrns,
    local.subnets_fqrns,
    local.bastions_fqrns,
    local.app1_nsgs_fqrns,
    local.app2_nsgs_fqrns,
  )

  # Unified FQRN map - merges ALL resources from all applications
  fqrns = merge(
    local.bastions_fqrns,
    local.compartments_fqrns,
    local.log_groups_fqrns,
    local.vcns_fqrns,
    local.subnets_fqrns,
    local.infra_zones_fqrns,
    local.app1_compute_instances_fqrns,
    local.app1_nsgs_fqrns,
    local.app2_nsgs_fqrns,
  )

  # Unified FQRN map for output (alias)
  unified_fqrn_map = local.fqrns
}
